version: '3.8'

services:
  frontend:
    build:
      context: ./path/to/frontend
      dockerfile: Dockerfile
    ports:
      - "80:80" 

  backend:
    build:
      context: ./path/to/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000" 

  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password

volumes:
  db_data:
